/** @type {import('@commitlint/types').UserConfig} */
export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    // Release commits and merge commits are generated by tooling.
    'header-max-length': [2, 'always', 100],
    'subject-case': [0],
  },
  ignores: [message => message.startsWith('Merge ') || message.startsWith('chore(release):')],
};
